apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tfm-deployer-role
  namespace: staging
rules:
  # Lectura general (observabilidad básica)
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "events"]
    verbs: ["get", "list", "watch"]

  # Configuración de la app (ConfigMaps/Secrets solo si tu app los usa)
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Ingress (K8s v1)
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
