# values-local.yaml - Adaptación de Spring PetClinic para el Chart Genérico

# 1. IMAGEN
image:
  repository: "jolrojasbodev/spring-petclinic"
  pullPolicy: IfNotPresent

# 2. RED Y PUERTOS (CORREGIDO: Volvemos a ClusterIP)
# Dejamos que Helm cree un servicio interno. 
# El acceso externo lo maneja nuestro archivo 'petclinic-nodeport.yaml' en el puerto 30080.
service:
  type: ClusterIP   # <--- CAMBIO: Volvemos a interno para eliminar el puerto aleatorio extra
  port: 8080
  targetPort: 8080

# 3. VARIABLES DE ENTORNO
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "mysql"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://mysql-db:3306/petclinic"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password

# 4. SONDAS DE VIDA
readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 40
  periodSeconds: 15

# 5. RECURSOS
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

# 6. INGRESS
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: petclinic.local
      paths:
        - path: /
          pathType: Prefix